{
 "title": "MollySocket",
 "tags": [
  "UnifiedPush",
  "Apps",
  "Signal",
  "Molly"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mollysocket_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reconnections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mollysocket_reconnections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pushes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mollysocket_pushs)by(type)", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mollysocket_messages)by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "mollysocket_connections", "legendFormat": "{{ namespace }}/{{ pod }}" }
   ]
  },
  {
   "title": "Reconnection (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "irate(mollysocket_reconnections[$__interval])",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  { "title": "Push (Rate)", "type": "timeseries", "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 } },
  {
   "title": "Messages (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "irate(mollysocket_messages[$__interval])",
     "legendFormat": "{{ namespace }}/{{ pod }}/{{ type }}"
    }
   ]
  }
 ]
}